#!groovy
//@Library('appsbroker_jenkins_library') _

pipeline {
    agent {
        docker {
            // Pin this to a specific terraform version if necessary
            image 'google/cloud-sdk:latest'
            args '--entrypoint="" -u root'
        }
    }
    parameters {
        choice(
            name: 'IMAGE_NAME',
            choices: ['php-fpm','nginx'],
            description: 'The image to build.' )
        booleanParam(name: 'DEBUG', defaultValue: true, description: '')
    }
    options {
        ansiColor('xterm')
    }
    environment {
        JENKINS_GCP_SVC = credentials("jenkins-gcp-service-account")
    }
    stages {
        stage('Pre-Deploy Checks') {
            steps {
                // For debugging purposes only
                sh "env"
            }
        }
        stage('Cloud Build Image') {
            steps {
                sh "gcloud auth activate-service-account jenkins@appsbroker-356110.iam.gserviceaccount.com --key-file=${JENKINS_GCP_SVC}"
                sh "'${WORKSPACE}/docker/scripts/cloud_build.sh' -i '${IMAGE_NAME}'"
            }
        }
    }
    post {
        always {
            echo 'The END.'
        }
    }
}
