#!groovy
//@Library('jenkins_library') _

pipeline {
    agent {
        label 'master'
    }
    parameters {
        extendedChoice(
            name: 'IMAGES',
            description: 'List of latest php images',
            multiSelectDelimiter: ',',
            visibleItemCount: 10,
            quoteValue: false,
            type: 'PT_SINGLE_SELECT',
            /* Values List Settings */
            groovyScript: fetchLatestImages('php')
            )
        choice(
            name: 'TARGET_ENVIRONMENT',
            choices: ['qa','prod'],
            description: 'The environment to deploy to.' )
        booleanParam(name: 'DEBUG', defaultValue: true, description: '')
    }
    environment {
        GKE_CLIENT_CERTIFICATE     = credentials("${params.target_environment}-gke-client-certificate")
        GKE_CLIENT_KEY             = credentials("${params.target_environment}-gke-client-key")
        GKE_CLUSTER_CA_CERTIFICATE = credentials("${params.target_environment}-gke-cluster-ca-certificate")
    }
    options {
        ansiColor('xterm')
    }
    stages {
        stage('Pre-Deploy Checks') {
            steps {
                displayEnvironmentInfo()
            }
        }
        stage('Deploy To QA') {
            when {
                environment name: 'TARGET_ENVIRONMENT', value: 'qa'
            }
            steps {
                deployGKEImage("QA GKE HOST HERE")
            }
        }
        stage('Deploy To PROD') {
            when {
                environment name: 'TARGET_ENVIRONMENT', value: 'prod'
            }
            steps {
                deployGKEImage("PROD GKE HOST HERE")
            }
        }
    }
    post {
        always {
            echo 'The END.'
        }
        success {
            echo 'Deployment Successful.'
        }
        failure {
            echo 'Deployment Failed.'
        }
    }
}
