steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "eu.gcr.io/${PROJECT_ID}/nginx:latest", "-t", "eu.gcr.io/${PROJECT_ID}/nginx:${_VERSION}", "."]
images:
- eu.gcr.io/${PROJECT_ID}/nginx
