apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsbroker
  labels:
    app: appsbroker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: eu.gcr.io/appsbroker-356110/nginx:latest
          ports:
            - containerPort: 80
        - name: php
          image: eu.gcr.io/appsbroker-356110/php-fpm:latest
          ports:
            - containerPort: 9000
