---
#
# This is a role based playbook. Roles are pulled in based on host group or host (for host specific roles typically for hardware support).
#

# Configure Jenkins
- name: Install and configure Jenkins
  hosts: jenkins
  become: yes
  roles:
    - jenkins

# Configure Gitlab
- name: Install and configure Gitlab
  hosts: gitlab
  become: yes
  roles:
    - gitlab
