steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "--build-arg", "ENV=${_ENV}", "-t", "us.gcr.io/${PROJECT_ID}/php:latest", "-t", "us.gcr.io/${PROJECT_ID}/php:${_VERSION}", "."]
images:
- us.gcr.io/${PROJECT_ID}/php
