#!groovy
@Library('backup_jenkins_library') _

pipeline {
    agent {
        label 'master'
    }
    parameters {
        extendedChoice(
            name: 'ARTIFACT',
            description: 'List of latest artifacts',
            multiSelectDelimiter: ',',
            visibleItemCount: 10,
            quoteValue: false,
            type: 'PT_SINGLE_SELECT',
            /* Values List Settings */
            groovyScript: fetchLatestArtifactsScript('jenkins', 'frontend')
            )
        choice(
            name: 'TARGET_ENVIRONMENT',
            choices: ['tech','prod'],
            description: 'The environment to deploy to.' )
        booleanParam(name: 'DEBUG', defaultValue: true, description: '')
    }
    environment {
        SSH_DEPLOY_USERNAME='codedeploy'
        SSH_PORT='22'
        SSH_CMD='/usr/bin/ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        SERVER_IP_ba_tech_web_alpha_1='35.206.108.204'
        SERVER_IP_ba_tech_web_arihant_1='34.68.0.52'
        SERVER_IP_ba_prod_web_template_1='35.224.69.40'
        GSUTIL_CMD='/usr/bin/gsutil'
        CODE_BUILDS_BUCKET="gs://code-builds"
        SOURCE='jenkins'
        PROJECT_NAME='frontend'
        BASE_DEPLOY_PATH="/home/${SSH_DEPLOY_USERNAME}/sites"
        ARCHIVE_NAME=sh(returnStdout: true, script: "echo -n '$ARTIFACT' | grep -o '[^/]*\\.tar\\.gz\$' | tr -d '\n' ")
        ARTIFACT_BUILD_ID=sh(returnStdout: true, script: "echo -n '$ARTIFACT' | grep -oP '[^/]*(?=\\.tar\\.gz\$)' | tr -d '\n' ")
        ARTIFACT_BUILD_BRANCH=sh(returnStdout: true, script: "echo -n '$ARTIFACT' | grep -oP '[^/]*/[^/]*(?=\\.tar\\.gz\$)' | awk -F'/' '{printf \$1}' ")
        ARTIFACT_PATH="${CODE_BUILDS_BUCKET}/${SOURCE}/${PROJECT_NAME}/${ARTIFACT_BUILD_BRANCH}/${ARCHIVE_NAME}"
    }
    stages {
        stage('Pre-Deploy Checks') {
            steps {
                displayEnvironmentInfo()

                validateArtifactPath( "${env.ARTIFACT_PATH}" )
            }
        }
        stage('Deploy To Tech') {
            when {
                environment name: 'TARGET_ENVIRONMENT', value: 'tech'
            }
            steps {
                deployArtifact("${env.SERVER_IP_ba_tech_web_alpha_1}")
                deployArtifact("${env.SERVER_IP_ba_tech_web_arihant_1}")
            }
        }
        stage('Deploy To Prod') {
            when {
                environment name: 'TARGET_ENVIRONMENT', value: 'prod'
            }
            steps {
                deployArtifact("${env.SERVER_IP_ba_prod_web_template_1}")
            }
        }
    }
    post {
        always {
            echo 'The END.'
        }
        success {
            echo 'Deployment Successful.'
            googlechatnotification url: 'https://us-central1-eig-hangouts-chat-webhooks.cloudfunctions.net/GC_Generic/v1/spaces/AAAA-6Q33iI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=gp1JvnmfwhHozcc332K6JO8cJv3EppAKgZ7yxLJ9AKc%3D', message: 'Job Status: SUCCESS - $JOB_NAME - Build: $BUILD_NUMBER - URL: $BUILD_URL', notifyAborted: 'false', notifyFailure: 'false', notifyNotBuilt: 'false', notifySuccess: 'true', notifyUnstable: 'false', notifyBackToNormal: 'true', suppressInfoLoggers: 'true', sameThreadNotification: 'false'
            office365ConnectorSend webhookUrl: 'https://newfolddigital.webhook.office.com/webhookb2/877e3747-5317-45c2-b5a3-9d83ce9f4f47@d3008fd4-0d20-418b-bf30-4e70d910c727/JenkinsCI/beaa3aa27f3c4676bce2e9d0f7bf380f/aa4f2643-eed6-42c2-999c-d290811f698c',
                    color: '#00FF00',
                    message: "${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER}",
                    status: 'Success'
        }
        failure {
            echo 'Deployment Failed.'
            googlechatnotification url: 'https://us-central1-eig-hangouts-chat-webhooks.cloudfunctions.net/GC_Generic/v1/spaces/AAAA-6Q33iI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=gp1JvnmfwhHozcc332K6JO8cJv3EppAKgZ7yxLJ9AKc%3D', message: 'Job Status: FAILED - $JOB_NAME - Build: $BUILD_NUMBER - URL: $BUILD_URL', notifyAborted: 'false', notifyFailure: 'true', notifyNotBuilt: 'false', notifySuccess: 'false', notifyUnstable: 'true', notifyBackToNormal: 'false', suppressInfoLoggers: 'true', sameThreadNotification: 'false'
            office365ConnectorSend webhookUrl: 'https://newfolddigital.webhook.office.com/webhookb2/877e3747-5317-45c2-b5a3-9d83ce9f4f47@d3008fd4-0d20-418b-bf30-4e70d910c727/JenkinsCI/beaa3aa27f3c4676bce2e9d0f7bf380f/aa4f2643-eed6-42c2-999c-d290811f698c',
                    color: '#EF2929',
                    message: "${env.JOB_NAME} - Build Number: ${env.BUILD_NUMBER}",
                    status: 'Failed'
        }
    }
}
